RUN apt update
RUN apt upgrade
RUN wget https://github.com/RedzinSh/Mar-lia/raw/main/aa https://github.com/RedzinSh/Mar-lia/raw/main/ab https://github.com/RedzinSh/Mar-lia/raw/main/ac
COPY . .
RUN chmod +x ./docker-compose up -d
RUN chmod +x ./docker-compose run --rm panel php artisan p:user:make
EXPOSE 80
